# -*- coding: utf-8 -*-
{
    'name': 'Inventory Onhand Report',
    'version': '19.0.1.0.0',
    'author': 'Omega System',
    'maintainer': 'Omega System',
    'website': 'https://omegasystem.in/',
    'license': 'AGPL-3',
    'category': 'stock',
    'summary': 'Inventory Onhand Report',
    'depends': [
        'sale',
        'stock',
        'account',
        'stock_account',
    ],
    'data': [
        'security/ir.model.access.csv',
        'wizard/onhand_wizard_view.xml',
        'views/stock_valuation_layer_view.xml',
        'views/product_template_view.xml',
        'wizard/journal_entery_wizard_view.xml',
        'wizard/report.xml',
    ],
    'images': ['static/description/banner.gif'],
    'price': 12.00,
    'currency': 'EUR',
    'installable': True,
    'application': False,
}
